### ISSUE TITLE
Output image is very desaturated

### ISSUE THREAD

**Issue by solarbro** [abbassi007/Enhanced_Local_Tone_Mapping_TMO#1]
I ran some tests with images from the [HDR+ dataset](http://www.hdrplusdata.org/dataset.html) and the outputs look very desaturated.
Here's an example:
![result](https://user-images.githubusercontent.com/8610487/200707157-3df1a360-c0ca-46be-b6ed-e64eeee9ff94.png)

Does the algorithm expect a specific color space other than sRGB (perhaps linear?) or are there parameters that can be tweaked to improve the results?

Thanks!

**Comment by solarbro** [comment]
The results with linear color space are indeed as expected. Additionally, results are significantly better when using 16-bit colors. 8-bit colors results in some gnarly artefacts in shadowy regions.
![example_sihdr_2](https://user-images.githubusercontent.com/8610487/200715644-07fda22b-a360-44c0-a39d-1db8e5adabb0.png)

BTW, I changed the code in main to read image paths from command line so that it doesn't need to recompile each time. Let me know if you would like a pull request for that.

Thanks!

**Comment by abbassi007** [comment]
@solarbro hope you find your answer as you completed the issue. However, in the constant header file, you can play with constants, and specifically for the saturation you can change the constant '**s**'. 
And yes, you can send a pull request.

Thank you for your changes.

**Comment by solarbro** [comment]
Thanks, I'll test it out.

I'll create a PR when I have the chance. I had to replace your VS files with a cmake script coz I'm trying to create an automated batch processing workflow, and I don't want to submit those changes into your repo.

**Comment by abbassi007** [comment]
Okay, that makes sense.
